"""CounterNarrative — aggregate for contrarian analysis (BC-7).

Invariants (D-032 § c):
- bear_points must be non-empty (each ≤500 chars per audit-traceability)
- historical_analogs must contain at least one entry
- generated_at must not be in the future

MANDATORY per BR-6: triggered when bullish_ratio() > 0.8 on considered ticker.
Gates positive signal issuance per I-S13 (counter-narrative mandatory for hot-stocks).

LLM output constraints per D-032 § (g) + I-S1:
- bear_points: list[str] (text only; NO numeric scores; NO percentage phrasing)
- Anti-pattern: "approximately 18%" raises LlmOutputViolatesISOne in generator
- Each bear-point ≤500 chars per Q-S53-4 IMPL decision

I-S2: generated_at + trigger provide provenance.
I-S35: bear_points framed as risk considerations, not sell orders.
BR-10: no operator naming in bear_points.

Source: specs/tier2-feature/003-crowd-sentiment-pump-detection.md § B.1 + § B.3 UC-4.
ADR: agent-workspace/memory/decisions/032-S51-BC-7-architecture-crowd-sentiment.md (D-032 § c + g).
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import UTC, datetime

__all__ = ["CounterNarrative"]

_MAX_BEAR_POINT_CHARS = 500  # per Q-S53-4 IMPL decision + audit-traceability


@dataclass(frozen=True)
class CounterNarrative:
    """Aggregate for contrarian bear-point analysis.

    Generated by CounterNarrativeGeneratorPort (LLM-grounded per D-032 § g).
    Stored with non-empty bear_points + non-empty historical_analogs invariants.

    I-10: ZERO framework dependencies.
    """

    ticker: str
    generated_at: datetime
    trigger: str                             # e.g. "bullish_ratio_threshold_crossed"
    bear_points: tuple[str, ...]             # non-empty; each ≤500 chars
    historical_analogs: tuple[object, ...]   # non-empty; HistoricalAnalog objects
    failing_analog_details: tuple[object, ...]  # analogs with subsequent_return_12m < -0.10
    bullish_consensus_summary: tuple[str, ...]  # aggregated bullish points from active narratives

    def __post_init__(self) -> None:
        if not self.bear_points:
            raise ValueError("CounterNarrative.bear_points must be non-empty")
        for i, bp in enumerate(self.bear_points):
            if len(bp) > _MAX_BEAR_POINT_CHARS:
                raise ValueError(
                    f"CounterNarrative.bear_points[{i}] exceeds {_MAX_BEAR_POINT_CHARS} chars "
                    f"(got {len(bp)}); per Q-S53-4 IMPL + audit-traceability limit"
                )
        if not self.historical_analogs:
            raise ValueError(
                "CounterNarrative.historical_analogs must contain at least one entry"
            )
        if not self.ticker:
            raise ValueError("CounterNarrative.ticker must not be empty")
        now_utc = datetime.now(UTC)
        ts = self.generated_at
        ts_aware = ts if ts.tzinfo is not None else ts.replace(tzinfo=UTC)
        if ts_aware > now_utc:
            raise ValueError(
                f"CounterNarrative.generated_at must not be in the future; "
                f"got {self.generated_at!r}"
            )
