"""ChannelContent — raw fetched content value object.

Holds the verbatim content fetched from a KOL channel before LLM extraction.
This is an immutable value object representing a point-in-time fetch snapshot.
It is NOT a recommendation; it is the raw input to the LLM extractor (Track H).

Invariants:
- `source_url` must be non-empty (BR-1 provenance).
- `published_at` must not be in the future (spec § Deliverable 3 invariant).
- `raw_text` may be empty (e.g. video with captions pending transcription).

Source: specs/tier2-feature/002-influence-network-tracking.md § B.1 + § B.4.
ADR: agent-workspace/memory/decisions/027-S45-BC-6-architecture-influence-network.md (D-027 § b).
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import UTC, datetime

from packages.domain.influence.value_objects.channel_id import ChannelId

__all__ = ["ChannelContent"]


@dataclass(frozen=True, slots=True)
class ChannelContent:
    """Immutable snapshot of fetched channel content.

    `content_id`   — deterministic hash of source_url (generated by adapter).
    `channel_id`   — owning channel.
    `source_url`   — canonical public URL (provenance per BR-1 + I-S2).
    `published_at` — timestamp from the platform (NOT ingestion time).
    `raw_text`     — transcript or post body; may be empty pre-transcription.
    `media_urls`   — list of attached media URLs (video/audio/image).
    `fetched_at`   — wall clock at the time of fetch (I-S2 as-of).
    """

    content_id: str
    channel_id: ChannelId
    source_url: str
    published_at: datetime
    raw_text: str = ""
    media_urls: tuple[str, ...] = field(default_factory=tuple)
    fetched_at: datetime = field(default_factory=lambda: datetime.now(UTC))

    def __post_init__(self) -> None:
        if not self.content_id or not self.content_id.strip():
            raise ValueError("ChannelContent.content_id must be non-empty")
        if not self.source_url or not self.source_url.strip():
            raise ValueError(
                "ChannelContent.source_url must be non-empty (BR-1 provenance)"
            )
        now = datetime.now(UTC)
        # Normalise tz-naive published_at before comparison
        pub = self.published_at
        if pub.tzinfo is None:
            pub = pub.replace(tzinfo=UTC)
        if pub > now:
            raise ValueError(
                f"ChannelContent.published_at {self.published_at!r} is in the future; "
                "cannot record future content"
            )
